#!/bin/bash

# Fixed path in the repository for regression test data.
# Discussion of accessing paths relative to a script is found at:
# http://mywiki.wooledge.org/BashFAQ/028
ANOMTRANS_TEST_DATA_DIR_="${PWD}/test_regression_data" 

#rm -r Obj_test
mkdir Obj_test
cd Obj_test
CC=mpicc CXX=mpicxx ANOMTRANS_TEST_PROCS=24 ANOMTRANS_TEST_DATA_DIR=${ANOMTRANS_TEST_DATA_DIR_} cmake -DCMAKE_BUILD_TYPE=Debug ..
make
